services:
  # odoo:
  #   # image: odoo:17
  #   build: 
  #     context: ./
  #     args:
  #       - tag=odoo-lida:17
  #   depends_on:
  #     - db
  #   ports:
  #     - "10018:8069"
  #     - "20018:8072"
  #   # tty: true
  #   # command: --
  #   environment:
  #     HOST: db
  #     USER: ${POSTGRES_USER:-odoo}
  #     PASSWORD: ${POSTGRES_PASSWORD:-supersecret}
  #   volumes:
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro
  #     # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
  #     - ./config:/etc/odoo
  #     - ./addons:/mnt/extra-addons
  #     - ./l10n_ve:/mnt/l10n_ve_addons
  #     # - ./data:/var/lib/odoo
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://127.0.0.1:8069"]
  #     interval: 2s
  #     timeout: 10s
  #     retries: 30
  #   networks:
  #     - intranet

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      PGPASSWORD: '${POSTGRES_PASSWORD:-supersecret}'
      POSTGRES_USER: ${POSTGRES_USER:-odoo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-supersecret}
      PGDATA: '/var/lib/postgresql/data/pgdata'
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d postgres"]
      interval: 5s
      timeout: 20s
      retries: 10
    networks:
      - intranet

  adminer:
    image: adminer
    ports:
      - "${FORWARD_ADMINER_PORT:-8888}:8080"
    networks:
      - intranet

  mailpit:
    image: "axllent/mailpit:latest"
    ports:
      - "${FORWARD_MAILPIT_PORT:-1025}:1025"
      - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"
    networks:
      - intranet

networks:
  intranet:
    driver: bridge
